export { default as Educational } from './Educational.vue'
export { default as Blood } from './blood.vue'
export { default as Political } from './Political.vue'
export { default as Nation } from './nation.vue'
export { default as Passport } from './Passport.vue'
export { default as Matrimony } from './Matrimony.vue'
export { default as Trusteeship } from './Trusteeship.vue'
export { default as Reside } from './Reside.vue'
export { default as Service } from './Service.vue'
export { default as Disability } from './Disability.vue'
export { default as Disability2 } from './Disability2.vue'
export { default as Retire } from './Retire.vue'
export { default as Community } from './Community.vue'
export { default as Children } from './Children.vue'
export { default as Subsistence } from './Subsistence.vue'
export { default as Type } from './Type.vue'
export { default as Religion } from './Religion.vue'

